version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8999:80"
      - "5255:5255"
    restart: unless-stopped
    volumes:
      - "./RiderRemoteDebuggingWithDockerSample/bin/Debug/net6.0:/app"
    command: ["concurrently", "/root/.local/share/JetBrains/DebuggerAgent -port=5255", "dotnet RiderRemoteDebuggingWithDockerSample.dll"]